version: '2'

# Compose configuration for running both Clio and Elasticsearch locally for integration-testing.
services:
  # NOTE: The integration test code relies upon this service being named `clio-server`
  # If you change this name, you need to update the `DockerIntegrationSpec` to match
  clio-server:
    image: broadinstitute/clio-server:${CLIO_DOCKER_TAG}
    environment:
      JAVA_OPTS: -Dclio.server.elasticsearch.http-hosts.0.hostname=elasticsearch1 -Dlogback.configurationFile=/app/clio-logback.xml
    networks:
      - clio-network
    volumes:
      - ${CONF_DIR}/clio-logback.xml:/app/clio-logback.xml
      - ${CLIO_LOG_FILE}:/logs/clio.log

  # NOTE: The integration test code relies upon this service being named `elasticsearch1`
  # If you change this name, you also need to update the `FullDockerIntegrationSpec`
  elasticsearch1:
    extends:
      file: elasticsearch-compose.yml
      service: elasticsearch
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ${LOG_DIR}/elasticsearch1:/usr/share/elasticsearch/logs
    networks:
      - clio-network

  elasticsearch2:
    extends:
      file: elasticsearch-compose.yml
      service: elasticsearch
    volumes:
      - esdata2:/usr/share/elasticsearch/data
      - ${LOG_DIR}/elasticsearch2:/usr/share/elasticsearch/logs
    networks:
      - clio-network
    environment:
      discovery.zen.ping.unicast.hosts: elasticsearch1

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  clio-network:
