version: 2

group_defaults:
  always_pending:
    labels:
      - do-not-merge
      - needs-rebase
      - work-in-progress
  approve_by_comment:
    enabled: true
    approve_regex: '^:+1:'
  author_approval:
    ignored: true
  teams:
    - dsde-pipelines-developers

groups:
  develop-reviewers:
    required: 2
    conditions:
      branches:
        - develop
  other-branch-reviewers:
    required: 1
